### ISSUE TITLE
App Namen

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/planty-backend#22]
Jetzt, da wir mit planty mehrere Steckbriefe und somit mehrere nicht zusammenhängende models haben, ist die App namensgebung `planty_content` etwas sperrig.

Besser wäre hier die Namenswahl `planty_reben_content` gewesen um nun `planty_pflanzen_content` für abzugrenzung der Steckbriefe der Gehölzer, Krautigen und Kulturpflanzen zunutzen.

Hier wäre in Zukunft eine Umbennenung der Django app nötig, dazu [hier](https://github.com/odwyersoftware/django-rename-app) mehr.

**Comment by ypeters** [comment]
Von unserer Seite gerne!
