### ISSUE TITLE
Mailadresse Kontakt/Feedback

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/planty-backend#25]
Die Feedback-Mails, die aus Planty über den contact-Endpoint geschickt werden, sollen an `Planty@hs-gm.de` versandt werden.
Der Projektname (`[PLANTY2Learn]`) sollte im Betreff eingefügt werden.

**Comment by sheepyhollow** [comment]
Wir haben uns b.a.w. darauf geeinigt, dass Planty uns technische Sachen Anfragen/Feedback weiterleitet. Das lassen wir erstmal so laufen.

Ist die Änderung der Mail eigentlich Arbeit am Code oder nur eine config/.env-Sache?

**Comment by chgad** [comment]
Also SOLID TEAM bekommt keine mails mehr direkt von studierenden?

**Comment by sheepyhollow** [comment]
Das war so die Idee. Aber eigentlich spricht auch nichts dagegen, die Mail auch in Kopie an unsere dlist zu versenden... 😅 
Ich denke, so sollten wir das lieber machen. @LarsWars ?

**Comment by chgad** [comment]
das geht leider nicht zum jetzigen Stand.

**Comment by chgad** [comment]
Also bleibt die Systemmail adresse weiterhin unsere dlist ?

> Ist die Änderung der Mail eigentlich Arbeit am Code oder nur eine config/.env-Sache?

Es ist eine reine env sache.
