### ISSUE TITLE
Titel der Steckbriefe = botanischer Name

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#46]
Aktuell wird der Titel noch durch den deutschen Namen generiert, hier bitte den botanischen Namen verwenden. 

@sheepyhollow

**Comment by sheepyhollow** [comment]
Ich verschiebe mal ins Backend, den das müsste hier passieren.

**Comment by ypeters** [comment]
Super danke dir! Ich füge alle Issues einfach mal ein, und du kannst sie dann in den richtigen Bereich schieben, wenn ich mich irren sollte.

**Comment by ypeters** [comment]
Gerne botanischer Name als Titel und deutscher Name als Untertitel :)

name = bot_name
sub_name = de_title

**Comment by chgad** [comment]
ich finde beim Plant model keinen de_title?!?!

**Comment by ypeters** [comment]
hab ehrlichweise die Bezeichnung von @sheepyhollow übernommen ;)

**Comment by sheepyhollow** [comment]
Sorry, den gab es vorher in "Living". Das ist jetzt bereits `name` in `general_information`.
D.h. es müsste so sein:

`general_information.sub_name = general_information.name`

`general_information.name = living.bot_name`

Dann müssten wir aber das Frontend noch so umbauen, dass wir 'sub_name` einfügen - ich weiß gerade nicht, ob das schon gemacht wurde. Ist aber easy. Dann muss im GeoMat-Backend und Div-e der `trivial_name` in `sub_name` umbenannt werden.

**Comment by chgad** [comment]
-.- Christian is not amused...

**Comment by sheepyhollow** [comment]
Das war leider bei der ersten Steckbriefdefinition von `plant` nicht präzise benannt.
