### ISSUE TITLE
Änderungen in Dropdown Menüs

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#47]
Tippfehler - Lebensweise Lebensdauer: Fragezeichen hinter <50 wurde entfernt (neue alphabetische Liste anbei) [Lebensdauer_230712.txt](https://github.com/zentrumnawi/planty-backend/files/12037872/Lebensdauer_230712.txt)

 [Giftigkeit_230712.txt](https://github.com/zentrumnawi/planty-backend/files/12037871/Giftigkeit_230712.txt) bitte um „Nadeln giftig“, „Nadeln leicht giftig“ und „Nadeln stark giftig“ ergänzen (neue alphabetische Liste anbei)

@chgad

**Comment by chgad** [comment]
Da kann ich euch nicht garantieren, dass es nicht bei irgendwelchen bereits bestehenden Steckbriefen zu änderungen kommt.

**Comment by chgad** [comment]
Um sicherzustellen, dass jetzt keine Werte falsch zu geordnet werden, füge ich die erwähnten Werte hinten an.
