### ISSUE TITLE
Perspektivisch: Objekt-ID durch Titel ersetzbar? 

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#50]
![Objekt-ID](https://github.com/zentrumnawi/planty-backend/assets/132896759/79d83897-7271-42fd-b5f0-93a7be38e64b)

Wäre es an dieser Stelle möglich, die Objekt-ID durch den Pflanzentitel auszutauschen (also z.B. Living Object „Acer Alba“). 

Das würde die Zuordnung erleichtern. Aktuell haben wir nämlich ein paar „Objektleichen“ z. B. wenn der Steckbrief nicht final gespeichert wurde (weil Internetabbruch oder what ever), aber die Unterkategorien wie „Living Object“ schon gespeichert wurden. Da führt dann dazu, dass die Unter-Objekt-ID nicht immer z. B. 102 ist (siehe Screenshot).

Gerade wenn wir jetzt daran denken, dass mehr Pflanzenkategorien hinzukommen und auch unterschiedliche Tutoren daran arbeiten, könnte das zu mehr „Objektleichen“ und Chaos führen.

Evtl. könnte es auch helfen, wenn es hier kein Dropdown gäbe? Aber das kann ich nicht einschätzen...

@sheepyhollow @chgad

**Comment by chgad** [comment]
Dann brauche ich für jedes der Unterkategorie Drop-Downs ein Feld welches dort jeweils als Name angezeigt wird.

Oder soll das immer  der `bot_name` sein?

**Comment by vvvika** [comment]
bot_name wäre doch prima eindeutig, oder @ypeters ?

**Comment by ypeters** [comment]
Ja bot_name wäre ideal!
