### ISSUE TITLE
Felder werden auch ohne Inhalt angezeigt

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#52]
![Habitus und Erscheiniung Backend Sandbirke](https://github.com/zentrumnawi/planty-backend/assets/132896759/6b23f2cb-4f32-4632-a34d-04b0b0daa301)

Aktuell ist es so, dass Felder, die keinen Inhalt enthalten (siehe Screenshots zur Sandbirke) trotzdem dargestellt werden. 

@sheepyhollow @chgad 

![Habitus und Erscheinung Sandbirke Frontend](https://github.com/zentrumnawi/planty-backend/assets/132896759/68d55427-3689-4a54-9fff-a59373dae0e2)

**Comment by chgad** [comment]
Hehe du verwechselst hier Felder mit Unterkategorien. Alles "unter" Habitus und Erscheinung sind Unterkategorien.

Wollt ihr folglich, dass leere Unterkategorien nicht auftauchen? Somit würde auch "Habitus und Erscheinung" nicht erscheinen.

**Comment by sheepyhollow** [comment]
Wir können ggf. im Frontend entscheiden, die Überschriften nicht anzuzeigen, wenn das Feld leer ist. Aber über mehrere Ebenen wird das schwierig.

**Comment by vvvika** [comment]
jep, exakt. Die Unterkategorie soll nicht sichtbar sein, wenn die Felder leer bleiben.

**Comment by ypeters** [comment]
> Hehe du verwechselst hier Felder mit Unterkategorien. Alles "unter" Habitus und Erscheinung sind Unterkategorien.
> 
> Wollt ihr folglich, dass leere Unterkategorien nicht auftauchen? Somit würde auch "Habitus und Erscheinung" nicht erscheinen.

Hihi sorry, Unterkategorien...Ich hab bestimmt auch noch andere Sachen falsch benannt. 

Das ist in dem Fall natürlich ein Extrembeispiel. Ich hatte hier als Test einfach mal bei allen nix eingegeben. Das wird bei den Pflanzen ja eigentlich nie vorkommen. Aber war definitiv vorkommt, das "Rinde" keinen Content enthält (weil nur die Gehölze die haben)

**Comment by chgad** [comment]
![Screenshot from 2023-07-13 15-44-09](https://github.com/zentrumnawi/planty-backend/assets/21121667/97850a36-18e3-4b4e-984b-41bf1f454143)

Wie hier zu sehen ist, wird nicht für diese rubirk (würde im zweife `appearance` heißen) ausgegeben.

@sheepyhollow das Pinge ich mal zurück ins Frontend.

Wenn ich ins schmea schaue, steht da zwar `appearance` als required... was aber die Datenbank nicht fordert.

Wie sich raus stellt ist es durch die Serializer Definition passiert.

**Comment by ypeters** [comment]
> Wie habt ihr das Beispiel überhaupt hingekriegt? Zu welcher Pflanze gehört das ?

Wenn man auf der "oberen" Ebene beim Erstellen des Steckbriefs im Backend nicht über + nichts für habitus etc. anlegt, dann kann man trotzdem Speichern. Die Screenshots zeigen Frontend und Backend der Pflanze Sandbirke. Aber glaube das hast du dem Code nach zu schließen schon herausgefunden...ich war zu langsam

**Comment by chgad** [comment]
Jaja, andere Baustelle
