### ISSUE TITLE
Block Informatives (Frontend/ Backend) Vorschlag

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#54]
Zum Block "Informatives"

Unser Vorschlag wäre diesen Bereich wie bei Reben „Allgemein“ nennen und die folgenden Felder unterordnen:

•	Deutscher Name (außer er wird jetzt Subtitel) 
•	Relevante Sorten (aktuell unter Taxonomie und Lebensweise)
•	Ähnliche Arten / Differenzialmerkmale (aktuell unter Habitus)
•	Verortung am Hochschulstandort

Literatur bitte auf jeden Fall ganz ans Ende des Steckbriefes, nicht in den Block „Allgemein“ (aktuell Informatives)

Allerdings warten wir noch auf Rückmeldung der Fachexperten hierzu. Das ist nur unser Vorschlag (mit der Tutorin ;))

@sheepyhollow @chgad

**Comment by vvvika** [comment]
So, hier nun, nach einer Besprechung mit den Lehrenden ist dieses finale Briefing hier rausgekommen: 

Aktuell gibt es bei den Gehölzen (sowohl Laub- als auch Nadelgehölze) die Kategorie "Informatives". Diese sollte, ähnlich wie bei Rebsorten "**Allgemein**" heißen und **folgende Informationen enthalten**, wenn möglich:

- Herkunft
- Familie
- Relevante Sorten
- Verortung am Hochschulstandort

und ja, Literatur sollte ganz ans Ende des Steckbriefes. 

🍃

**Comment by vvvika** [comment]
Hallo in die Runde. Kann man dieses Issue wieder öffnen? Das finale Briefing ist ja schon da (siehe oben) und könnte somit wieder angegangen werden.

**Comment by ypeters** [comment]
![grafik](https://github.com/zentrumnawi/planty-backend/assets/132896759/4e009dd5-4b7d-44d6-ac2d-a176e43ce0f5)
