### ISSUE TITLE
Speicher/Server? Probleme beim Speichern der Bilder

### ISSUE THREAD

**Issue by ypeters** [zentrumnawi/planty-backend#57]
Unserer Tutorin fügt aktuell zu unseren Steckbriefen die Bilder hinzu und ist recht frustriert, weil sie immer wieder Fehlermeldungen bekommt. 

Sie fügt z. B. 11 Bilder inkl. Alt-Text zum Steckbrief hinzu und speichert und erhält dann beim Speichervorgang eine Fehlermeldung und der Speichervorgang ist im Anschluss nicht erfolgreich. D.h. sie muss das alles mehrfach machen und hoffen, dass der Speichervorgang klappt. 

Was funktioniert: die Bilder in "Portionen" hochzuladen, also z. B. 5 Bilder. 

Liegt das an der Dateigröße? GIbt es vielleicht ein Limit? Oder der Rückmeldedauer des Servers?

Aktuell speichert Jule jetzt immer in kleinen Portionen und muss daher aber auch immer alle Steckbriefe mehrfach anfassen.

**Comment by ypeters** [comment]
Was auch manchmal passiert: 

Manche Bilder werden einfach 3 mal gespeichert im gleichen Speichervorgang - also z. B. sind dann 3 x das Bild für "alte Rinde" gespeichert, dafür andere nicht...

**Comment by chgad** [comment]
> Sie fügt z. B. 11 Bilder inkl. Alt-Text zum Steckbrief hinzu und speichert und erhält dann beim Speichervorgang eine Fehlermeldung und der Speichervorgang ist im Anschluss nicht erfolgreich. D.h. sie muss das alles mehrfach machen und hoffen, dass der Speichervorgang klappt.
> 
> Was funktioniert: die Bilder in "Portionen" hochzuladen, also z. B. 5 Bilder.

Jo. Die Bilder die ihr hochladet sind ca. 3 MB groß. Unser CDN lässt maximal 20 MB pro Request zu --> maximal 6 Bilder à 3 MB.

> Manche Bilder werden einfach mehrfach gespeichert im gleichen Speichervorgang - also z. B. sind dann 3 x das Bild für "alte Rinde" oder 2 x "Habitus Sommer" gespeichert, dafür andere nicht...

Das kann ich jetzt nicht nachvollziehen.


Allgemein würde ich folgendes Vorgehen vorschlagen:

1. Alle Eingaben in Textform tätgen
2. Spiechern/Objekt erstellen
3. die ersten 6 Bilder einfügen
4. Speichern
5. Schritt 4&5 wiederholen.

**Comment by LarsWars** [comment]
> Was auch manchmal passiert:
> 
> Manche Bilder werden einfach mehrfach gespeichert im gleichen Speichervorgang - also z. B. sind dann 3 x das Bild für "alte Rinde" oder 2 x "Habitus Sommer" gespeichert, dafür andere nicht...
> 
> Wenn Jule sie dann löscht, erscheinen dafür auf einmal Bilder in der Liste, die vorher nicht angezeigt wurden...

Hi, haben die Bilder *dzi* in ihrem Namen? - auf dem Server werden mehrere Bilder in unterschiedlicher Größe und Auflösung für die "deep-zoom-option") abgelegt...
