### ISSUE TITLE
Diese Felder sollen als Freitextfelder definiert werden

### ISSUE THREAD

**Issue by vvvika** [zentrumnawi/planty-backend#64]
Hallo in die Planty-Runde.
Unsere Tutoren arbeiten fleißig im Backend und möchten gerne eine Änderung vorschlagen, die ihnen die Arbeit mit den Steckbriefen erleichtert; Wäre es möglich, folgende Felder in Freitext-Felder umzuwandeln?

**Blatt**: Randform / Zeitpunkt des Austriebs / Stellung
**Blüte**: Form der Einzelblüte / Alter bei erster Blüte
**Trieb**: Blattnarbe
**Wurzel**: Empfindlichkeit

🍃
viele Grüße,
Viktoria

**Comment by LarsWars** [comment]
Hi,
wie viele Zeichen sollen maximal rein?

**Comment by chgad** [comment]
@vvvika Bis nächsten Mitwoch 27.3. Bitte jedes Feld mit zugehöriger Zeichenanzahl hier rein.

**Comment by vvvika** [comment]
In der Hoffnung, dass ich die Nachricht richtig verstanden habe, fasse ich hich hier die Textfelder, die in Freitextfelder mit **250 Zeichen** umgewandelt werden sollten. (Ursprünglich habe ich 500 Zeichen geschrieben. Dies war  für denn Fall dass die Länge **aller** Freitextfelder einheitlich definiert werden müsste):

1. Habitus und Erscheinung > Trieb> **Blattnarbe** (hier und in den Folgenden Feldern: 250 Zeichen)

2. Habitus und Erscheinung > Blatt > **Randform** 
3. Habitus und Erscheinung > Blatt > **Stellung*** 
_4. Habitus und Erscheinung > Blatt > Zeitpunkt des Austriebs (??? Wird noch kurz geprüft)
5. Habitus und Erscheinung > Blatt > **Farbe**

6. Habitus und Erscheinung > Blüte> **Form der Einzelblüte**
7. Habitus und Erscheinung > Blüte> **Alter bei erster Blüte**

8. Habitus und Erscheinung > Trieb> **Blattnarbe**

9. Habitus und Erscheinung > Wurzel > **Empfindlichkeit**
