### ISSUE TITLE
Aktualisierte Liste der Pflanzenfamilien

### ISSUE THREAD

**Issue by vvvika** [zentrumnawi/planty-backend#65]
Hallo nach Frankfurt!

Hier kommt eine aktualisierte Liste (txt-Format als Download) der Pflanzenfamilien - alphabetisch sortiert nach botanischen Namen - mit einer großen **Bitte um Aktualisierung im Backend** 
(unter "_Taxonomie und Lebensweise_">> "Familie -botanischer Name (deutscher Name)"

![grafik](https://github.com/zentrumnawi/planty-backend/assets/95678980/673d4dd1-045a-4026-99a4-e68449f3761a)

🍃
[Familie_botanischerName_240220.txt](https://github.com/zentrumnawi/planty-backend/files/14348002/Familie_botanischerName_240220.txt)

Gruß,
Viktoria

**Comment by chgad** [comment]
Das funktioniert nicht sortiert, ich füge die differenz ans ende der Liste an.

**Comment by vvvika** [comment]
das habe ich leider nicht ganz verstanden. Kann man die Liste nicht einfach überschreiben?

**Comment by chgad** [comment]
Nein,  da nciht der in der Liste Aufgeführte Name gespeichert wird, sondern eine generierte Zahl.

Ich kann die ganze Liste überschreiben, dann muss aber bei jeder PFlanze überprüft werden ob die Familie noch stimmt.

Ich habe nicht damit gerechnet das nach so langer Zeit so grundlegende Änderungen an Auswahlfeldern anfallen.

Wenn ich da jetzt einen schnell fix finde, muss nichts geändert werden. Falls nicht, ist Option A) Neue Einträge ans ende stellen oder Option B alle Einträge nach überschreiben der Liste zu überprüfen.

**Comment by chgad** [comment]
Ich habe eine Lösung gefunden. Lediglich die 3 wegfallenden Auswahlmöglichkeiten müssen weiterhin drin stehen bleiben, ansonsten müsstet ihr wie in Option B vorgehen.
