### ISSUE TITLE
Änderungen der Steckbriefe

### ISSUE THREAD

**Issue by kerstinhartmann** [zentrumnawi/planty-backend#7]
Bei der weiteren Eingabe von Inhalten haben sich folgende Änderungswünsche beim Planty2Learn-Team ergeben: 

**Ausgewachsenes Blatt**
- [x] _Randform_ hinzufügen von Auswahlmöglichkeit "wechselnd gezähnt und gesägt"
- [x]  Eigenschaft _Anthocyanfärbung_ löschen

**Trauben** (Kategorie soll optional sein!)
- [x] _Dichte_ optional sowie Umsetzung in 2 Dropdownlisten sodass Von-Bis-Angaben möglich sind, z.B. Angabe "lockerbeerig bis mitteldicht"
- [x] _Größe ohne Stiel_ optional
- [x] _Form_ optional sowie Von-Bis-Angaben ermöglichen, z.B. Angabe "konisch bis zylindrisch"
- [x] _Geschultert_ optional

**Beeren** (Kategorie soll optional sein!)
- [x] _Form_ optional
- [x]  _Größe_ optional sowie Von-Bis-Angaben ermöglichen, z.B. Angabe "klein bis mittel"
- [x]  _Farbe_ optional
- [x] _Farbe des Fruchtfleischs_ optional

**Comment by chgad** [comment]
> Trauben (Kategorie soll optional sein!)

> Beeren (Kategorie soll optional sein!)

Beide Kategorieen sind Optional? Oder was meinst du damit?
